# Generated by Django 3.1.7 on 2021-09-10 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210909_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
